### ISSUE TITLE
Cannot find module '/usr/src/app/dist/tools/positions.js'

### ISSUE THREAD

**Issue by bennycode** [stoqey/ib#104]
When running `docker-compose up`, then I am getting the following error:

```
tws_1     | 2021-07-26 08:30:24:925 IBC: Using default settings provider: ini file is /opt/ibc/config.ini
tws_1     | 2021-07-26 08:30:24:926 IBC: Using default login manager: getting username and password from args but not found. Will get from settings
tws_1     | 2021-07-26 08:30:24:926 IBC: Using default main window manager: constructor parameter isGateway=true
tws_1     | 2021-07-26 08:30:24:926 IBC: Using default trading mode manager: constructor parameter args but trading mode not present - will be taken from settings
tws_1     | 2021-07-26 08:30:24:927 IBC: Using default config dialog manager
tws_1     | 2021-07-26 08:30:24:932 IBC: CommandServer is not started because the port is not configured
tws_1     | 2021-07-26 08:30:25:008 IBC: TWS Settings directory is: /root/Jts
tws_1     | 2021-07-26 08:30:25:009 IBC: Creating minimal /root/Jts/jts.ini
tws_1     | 2021-07-26 08:30:25:009 IBC:     jts.ini: [Logon]
tws_1     | 2021-07-26 08:30:25:010 IBC:     jts.ini: s3store=true
tws_1     | 2021-07-26 08:30:25:010 IBC:     jts.ini: Locale=en
tws_1     | 2021-07-26 08:30:25:010 IBC:     jts.ini: displayedproxymsg=1
tws_1     | 2021-07-26 08:30:25:010 IBC:     jts.ini: [IBGateway]
tws_1     | 2021-07-26 08:30:25:010 IBC:     jts.ini: ApiOnly=true
tws_1     | 2021-07-26 08:30:25:010 IBC: Starting session: will exit if login dialog is not displayed within 30 seconds
tws_1     | 2021-07-26 08:30:25:805 IBC: Getting config dialog
tws_1     | 2021-07-26 08:30:25:805 IBC: Creating config dialog future
tws_1     | 2021-07-26 08:30:25:806 IBC: Getting main window
tws_1     | 2021-07-26 08:30:25:806 IBC: Creating main window future
ib-api    | internal/modules/cjs/loader.js:905
ib-api    |   throw err;
ib-api    |   ^
ib-api    |
ib-api    | Error: Cannot find module '/usr/src/app/dist/tools/positions.js'
ib-api    |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
ib-api    |     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
ib-api    |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
ib-api    |     at internal/main/run_main_module.js:17:47 {
ib-api    |   code: 'MODULE_NOT_FOUND',
ib-api    |   requireStack: []
ib-api    | }
ib-api exited with code 1
```

Any tips why `/usr/src/app/dist/tools/positions.js` cannot be found?

**Comment by Tsopic** [comment]
Hey, please try to run yarn build. And let me know if it worked.

**Comment by Tsopic** [comment]
@bennycode

**Comment by bennycode** [comment]
Hi @Tsopic, I cloned this repo and executed all steps descripted in [test locally](https://github.com/stoqey/ib#locally). Unfortunately, it crashes on my end after the last build step:

```
Step 9/10 : ENV NODE_ENV development
 ---> Running in 8594b5a5914e
Removing intermediate container 8594b5a5914e
 ---> 996fb3732c20
Step 10/10 : CMD ["node","./dist/tools/positions.js", "-watch"]
 ---> Running in 96881fa0bc47
Removing intermediate container 96881fa0bc47
 ---> ff129a7b7581

Successfully built ff129a7b7581
Successfully tagged ib_ib-api:latest
WARNING: Image for service ib-api was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating ib_tws_1 ... done
Creating ib-api   ... error

ERROR: for ib-api  Cannot create container for service ib-api: Conflict. The container name "/ib-api" is already in use by container "fdb5e8893d149718d710db8b5c267ac2f7c8fb275c57ff017dadaec91bda2b02". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for ib-api  Cannot create container for service ib-api: Conflict. The container name "/ib-api" is already in use by container "fdb5e8893d149718d710db8b5c267ac2f7c8fb275c57ff017dadaec91bda2b02". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.
```

**Comment by Tsopic** [comment]
As error states it's already running. Please google next time before asking. Also you may create the PR to improve readme to help us improve the repo.

Solution here is to tear down old containers first.


Run:
docker-compose down && docker-compose up

**Comment by bennycode** [comment]
Sorry for causing you trouble. I am new to Docker and when executing `docker-compose down && docker-compose up`, then I am getting the same error:

```
C:\dev\projects\temp\ib>docker-compose down && docker-compose up
Removing network ib_default
WARNING: Network ib_default not found.
Creating network "ib_default" with the default driver
Creating ib_tws_1 ... done
Creating ib-api   ... error

ERROR: for ib-api  Cannot create container for service ib-api: Conflict. The container name "/ib-api" is already in use by container "fdb5e8893d149718d710db8b5c267ac2f7c8fb275c57ff017dadaec91bda2b02". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for ib-api  Cannot create container for service ib-api: Conflict. The container name "/ib-api" is already in use by container "fdb5e8893d149718d710db8b5c267ac2f7c8fb275c57ff017dadaec91bda2b02". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.
```

I am using Docker Desktop v3.5.2 and the latest version of your "master" branch (commit c65fcc8bbd440b022b9f6f189daa730479a7bf7a).

**Comment by mfrener** [comment]
< Docker Desktop v3.5.2
Means on your Container/Apps tab there is container running, that needs the ib-api image (Image tab), so it cannot be re-created.
Stop all running containers first.

**Comment by bennycode** [comment]
Thanks for the hint. 👍 I removed all my builds from the "Containers/Apps" section and now it's almost starting (still the error with `Cannot find module '/usr/src/app/dist/tools/positions.js'`).

@Tsopic, I tried to run `yarn build` to compile `positions.ts` but it's not working on Windows. The `build` script uses `rm -rf dist` which is not available on Windows. To achieve cross-platform compatibility the `rm -rf` command could be replaced with a tool like [rimraf](https://github.com/isaacs/rimraf). Would you accept a PR for that?

**Comment by mfrener** [comment]
@bennycode I would recommend getting those tools for windows, as it is quite common on node projects to just use linux tools (you will run into that issue over and over again). I'm also on Windows + https://www.cygwin.com/ (cygwin is collection of Linux tools + libs, ported to windows, including all the shell tools such rm, but also more advanced stuff such gcc if, if you need it (you can select what you want)).

**Comment by bennycode** [comment]
Ok. For now I fixed the "clean" script in my local clone of "stoqey/ib". 

Executing "yarn build" before running `docker-compose up` helped to get rid off the error with "positions.js". I see now a lot of repeating "ERROR: Cannot disconnect if already disconnected" statements in my console. Is this good to go?

![image](https://user-images.githubusercontent.com/469989/126970911-d63b0f49-9b18-4a8d-a57a-bfee1df18dd7.png)

My `.env` file looks like this:

```
NODE_ENV=development
ENV_CONFIG_TEST=ENV
LOCAL_CONFIG_TEST=local
IB_PORT=4002
TRADING_MODE=paper
TWS_USERID=top
TWS_PASSWORD=secret
```

**Comment by mfrener** [comment]
Use IB_PORT=4004. The IBGateway only accepts connections from localhost on default config and since we do not want to change config, we run a proxy that maps 4004->4002 and 4003->4001. So to talk to 4002 from outside, use 4004. 
(not sure if that docker is designed for "standalone usage", it's part of our CI).

**Comment by bennycode** [comment]
Thanks for taking the time to debug this with me. I have set `IB_PORT` to `4004` in my `.env` file and now it looks like I can connect to the gateway.

I used the demo code from your examples in my TS application:

```ts
import Ib, {ErrorCode, EventName} from '@stoqey/ib';

const ib = new Ib({
  host: '127.0.0.1',
  port: 4004,
});

let positionsCount = 0;

ib.on(EventName.error, (err: Error, code: ErrorCode, reqId: number) => {
  console.error(`${err.message} - code: ${code} - reqId: ${reqId}`);
})
.on(EventName.position, () => {
  positionsCount++;
})
.once(EventName.positionEnd, () => {
  console.log(`Total: ${positionsCount} positions.`);
  ib.disconnect();
});
```

It now fails with this message:

```
Server Version 0: It does not support position requests. - code: 503 - reqId: -1
```

So we are one step further! 😀 

Which Docker image do you recommend for "standalone usage"? In my own application I just did `yarn add @stoqey/ib` but this just downloads the compiled JS code and type definitions. I am now wondering how I can fully use your project to run trades on IBKR?

**Comment by mfrener** [comment]
"Server Version 0:" error means you not connected yet (TCP connection is up, but handshake not completed). 
If the positions.js works (that is IBApiNext), but the sample code doesn't anymore (that is IBApi):
move the `ib.reqPositions();` to into a:
ib.on(EventName.connected, () => {
   ib.reqPositions();
});
If this solves, I will have a look (than send out requests too early, in between the handshake not after completed), shouldn't happen).

>Which Docker image do you recommend for "standalone usage"? In my own application I just did yarn add @stoqey/ib but this just downloads the compiled JS code and type definitions. I am now wondering how I can fully use your project to run trades on IBKR?

For getting started, I recommend installing IB Gateway or TWS locally. So you can focus app instead of fiddling around with infrastructure.
If want to dockerize it, there are many images for IBC arround (IBC /IBCalpha is a tool run gateway from command line), but almost always want to do modify it. So best here is get into docker and create your own, that fits to what you need. Like here is one I made https://github.com/mfrener/ib-gateway-docker-headless (also uses proxy), but I don't use it anymore, instead I have decided to run a Typescript App that does a REST server all in same container, that would be this https://github.com/waytrade/ib-api-service / https://github.com/waytrade/ib-api-service/blob/master/Dockerfile  (as you see, really depends on how you want to set it up / configure it)

**Comment by bennycode** [comment]
Thank you for the detailed explanation. I now understood what your library does behind the scenes: It actually forwards requests to the IB Gateway. 

I got it running now by doing the following:

1. Starting "IB Gateway" Version 985.1g ([IB Gateway Latest for Windows](https://www.interactivebrokers.com/en/index.php?f=16454))
2. Logging in to "IB Gateway" in "Paper Trading" mode (IB Gateway will now be locally accessible on Port 4002, Socket port can be configured in "Configure" > "Settings" > "API" > "Settings")
3. Using `IBApi` in my demo script (instead of using the `default Ib` export which seems to be referring to `IBApiNext`)

```ts
import {IBApi, Contract, ErrorCode, EventName} from '@stoqey/ib';

const ib = new IBApi({
  port: 4002,
});

let positionsCount = 0;

ib.on(EventName.error, (err: Error, code: ErrorCode, reqId: number) => {
  console.error(`${err.message} - code: ${code} - reqId: ${reqId}`);
})
.on(EventName.position, (account: string, contract: Contract, pos: number, avgCost: number) => {
  console.log(`${account}: ${pos} x ${contract.symbol} @ ${avgCost}`);
  positionsCount++;
})
.once(EventName.positionEnd, () => {
  console.log(`Total: ${positionsCount} positions.`);
  ib.disconnect();
});

ib.connect();
ib.reqPositions();
```

I can now work with it while the IB-Gateway program is running. Thank you! I am really happy that you provide a TypeScript library to communicate with the IBKR API. 😊

**Comment by bennycode** [comment]
> @bennycode I would recommend getting those tools for windows, as it is quite common on node projects to just use linux tools (you will run into that issue over and over again). I'm also on Windows + https://www.cygwin.com/ (cygwin is collection of Linux tools + libs, ported to windows, including all the shell tools such rm, ls, cp, ..., but also more advanced stuff such gcc if, if you need it (you can select what you want)).

Hey @mfrener, I appreciate your recommendation. I came back here because your view on this matter kept me thinking for quite some time. I was never really happy with Cygwin or MinGW as there was always a mismatch between what was available for Linux and what has been ported for Windows. Luckily, I found out about [WSL](https://github.com/MicrosoftDocs/WSL) and made a tutorial about it where I feature `@stoqey/ib`. 😀 https://www.youtube.com/watch?v=bRW5r7TK6KM
