### ISSUE TITLE
Commission returns incorrect large number

### ISSUE THREAD

**Issue by pistachiomatt** [stoqey/ib#107]
Hello! Thanks for building such a great and thorough library. I'm seeing this bug when executing any order on my paper trading account:

```
const ib = new IBApi({port: PORT})
ib.connect(clientId)
ib.on(EventName.openOrder, (orderId, contract, order, orderState) => {
  console.log(orderState)
})


=> {
  status: 'PreSubmitted',
  initMarginBefore: 1.7976931348623157e+308,
  maintMarginBefore: 1.7976931348623157e+308,
  equityWithLoanBefore: 1.7976931348623157e+308,
  initMarginChange: 1.7976931348623157e+308,
  maintMarginChange: 1.7976931348623157e+308,
  equityWithLoanChange: 1.7976931348623157e+308,
  initMarginAfter: 1.7976931348623157e+308,
  maintMarginAfter: 1.7976931348623157e+308,
  equityWithLoanAfter: 1.7976931348623157e+308,
  commission: 1.7976931348623157e+308,
  minCommission: 1.7976931348623157e+308,
  maxCommission: 1.7976931348623157e+308,
  commissionCurrency: '',
  warningText: ''
}
```

If I was being charged fees totalling more than the GDP of every nation in the world, I'd be a bit annoyed 😉 I'm not sure what the issue is.

My real account is a standard individual's account with the Pro tier. Orders executed both in the API and manually produce actual fees of USD$1.00 (in the real account; not sure how to see fees in Trader Workstation to verify what the paper trading account's fees are.)

**Comment by mfrener** [comment]
The 1.7976931348623157e+308 is Number.MAX_SAFE_INTEGER.
Have implemented it like that to be in-line with official IB Java API which does use Long.MAX_VALUE.
In general this means that value is not available. 
I'm aware of that Jscript/TS has undefined for such cases, and on IBApiNext we have dropped Number.MAX_SAFE_INTEGER in favor of undefined, however on IBApi it still is Number.MAX_SAFE_INTEGER so that we stay as close as possible to original API.
However... as you are not the first one reporting this, I slowly think it might be a good idea to also IBApi from Number.MAX_SAFE_INTEGER to undefined... hmm

**Comment by pistachiomatt** [comment]
Thanks for replying. Yeah, I'd agree and recommend it too— I believe "staying true to the API" means the method names and response signatures should be the same, but language-specific things should be converted to native to the language the library is in. It's never convention in JS to return a large number when null or undefined is intended. First for me! I have to coerce every field now!

**Comment by mfrener** [comment]
> It's never convention in JS to return a large number when null or undefined is intended.
It's also convention on Java (there it would be null) nor somewhere else, more like IB specific thing, they have more such pitfalls (such as a bid/ask size or price of -1 means means "no bid/ask", not like... a oil future trading at negative price ;) )

You can do this as quick solution, so you don't need to check every number but the orderState only:
`function undefineMaxAttributes<T>(obj: T): T {
  Object.keys(obj).forEach(key => {
    if ((<Record<string, number>>(<unknown>obj))[key] === Number.MAX_VALUE) {
      delete (<Record<string, number>>(<unknown>obj))[key];
    }
  });
  return obj;
}
..
orderState = undefineMaxAttributes(orderState);
`

Will do a PR to change it and keep this issue open until merged to master.

**Comment by mfrener** [comment]
PR open https://github.com/stoqey/ib/pull/108

**Comment by mfrener** [comment]
@pistachiomatt if you have 15min, can you please verify https://github.com/stoqey/ib/pull/108 works for you as expected?
How to test:
> git clone https://github.com/stoqey/ib.git
> cd ib
> git checkout --track origin/no-more-max-number
> yarn install
> yarn build

Copy the ./dist folder over to your project's ./node_modules/@stoqey/ib/dist and try again.
