### ISSUE TITLE
Can you return promise from IbApiNext.connect()?

### ISSUE THREAD

**Issue by IldarDavletyarov** [stoqey/ib#125]
After connecting, I have to execute sleep function (`const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms)`) in the code so that the system has time to connect and then perform operations.

Can IbApiNext return a promise to not rely on setTimeout?

## Now:
```
ib.connect();

sleep(1000) // 🤮
.then(() => {
  positionsSubscription = ib.getPositions().subscribe(_ => positions = _);
})
```

## Would like:
```
ib.connect()
.then(() => {
  positionsSubscription = ib.getPositions().subscribe(_ => positions = _);
})
```

**Comment by mfrener** [comment]
You don't need to. 
ib.getPositions().subscribe does not send a request to TWS immediately (so there is also no need to be connected).
Instead IBApiNext will create a subscription object, representing your getPositions subscription.
Such a subscription object will send the TWS request on "connected" events.
So the underlying connection is kind of de-coupled.
Example - this will work;
`
positionsSubscription = ib.getPositions().subscribe(_ => positions = _);

ib.connect();
sleep(1000) 
.then(() => {
  ib.disconnect();
  sleep(1000) 
  .then(() => {
    ib.connect();
  })
})

notice the single "getPositions().subscribe", no need to re-subscribe on connection state changes.

`

**Comment by IldarDavletyarov** [comment]
Thank you so much for your help!

I am currently developing a system that will send signals continuously (up to 300 per day). Can you tell me if it will be possible to keep the connection open all the time? And also, is it optimal to open a separate connection for each signal?

I apologize in advance, but there is no one to ask.

**Comment by mfrener** [comment]
> I am currently developing a system that will send signals continuously (up to 300 per day). Can you tell me if it will be possible to keep the connection open all the time? And also, is it optimal to open a separate connection for each signal?

IBApiNext can do that for you.
When you do 'new IBApiNext(options)', you can pass in a IBApiNextCreationOptions object, which two attributes relevant for you:
```
/**
   * The auto-reconnect interval in milliseconds.
   * If 0 or undefined, auto-reconnect will be disabled.
   */
  reconnectInterval?: number;

  /**
   * The connection-watchdog timeout interval in seconds.
   *
   * The connection-watchdog monitors the socket connection to TWS/IB Gateway for
   * activity and triggers a re-connect if TWS/IB Gateway does not response within
   * the given amount of time.
   * If 0 or undefined, the connection-watchdog will be disabled.
   */
  connectionWatchdogInterval?: number;
```
So you can use reconnectInterval to let IBApiNext automatically re-connect after a certain interval if connection got lost. Example: in daily Gateway restart, your app can stay running. Connection will drop, Gateway will restart, while IBApiNext tries to re-connect every reconnectInterval seconds until is connected again.
connectionWatchdogInterval is an additional layer of security to also detect connect or gateway "hangs". It will constatly poll gateway and if it doesn't response within connectionWatchdogInterval, connection will be dropped and re-connected after reconnectInterval.

You can also observe the current connection state by using IBApiNext.connectionState.subscribe(..)

So I would do like this:
Subscribe on market data, position, account summary, ... so generate your signal.
Set a reconnectInterval, to e.g. 30s.
Call IBApiNext.connect()
and watch signals all year long without and reboot or re-subscribe or re-connect.
