### ISSUE TITLE
cancelOrder does not work

### ISSUE THREAD

**Issue by IldarDavletyarov** [stoqey/ib#129]
### Firstly, I open SELL LMT order (take profit order):
```
const contract: Contract = {
    secType: SecType.CASH,
    currency: 'USD',
    symbol: 'EUR',
    exchange: 'IDEALPRO',
}

const order: Order = {
  orderType: OrderType.LMT,
  action: OrderAction.SELL,
  lmtPrice: 6.057,
  totalQuantity: TOTAL_QUANTITY,
};

const orderId = await ib.placeNewOrder(contract, order); // 42

// place orderId to mongoDB
```

### Secondly, I want to change take profit: cancel first order and place new order with new lmtPrice:
```
const takeProfitOrderId = getFromMongoDb(); // 42
const contract: Contract = {
    secType: SecType.CASH,
    currency: 'EUR',
    symbol: 'USD',
    exchange: 'IDEALPRO',
}

const order: Order = {
  orderType: OrderType.LMT,
  action: OrderAction.SELL,
  lmtPrice: 7.057,
  totalQuantity: TOTAL_QUANTITY,
};

ib.cancelOrder(takeProfitOrderId);
await sleep(50);
ib.modifyOrder(takeProfitOrderId, contract, order);
```
### But first order does not canceled: I have 2 open orders in TWS:
<img width="1745" alt="image" src="https://user-images.githubusercontent.com/42977192/140984313-c12624f3-bcc1-4440-b20a-abd7e7c51165.png">

Please Help

**Comment by IldarDavletyarov** [comment]
By the way, between placing orders I reboot my scripts (disconnect and connect)

**Comment by mfrener** [comment]
> By the way, between placing orders I reboot my scripts (disconnect and connect)
That could be a reason. OrderId resets, although not sure if for every connection or only on TWS reboot - @Tsopic might be able to answer.

**Comment by IldarDavletyarov** [comment]
> Add a
> 
> ```
> ib.error.ssubscribe((error) => {
>       console.error(`${error.error.message}`);
> });
> ```
> 
> somewhere and watch the console: any error messages from TWS?

There are no errors in console, a new order is placed without problems, and the previous order is not deleted.

**Comment by mfrener** [comment]
btw feel free to join us on Slack, usually the better to place to ask questions than here ;) https://github.com/stoqey/ib/discussions/26

**Comment by mfrener** [comment]
> There are no errors in console, a new order is placed without problems, and the previous order is not deleted.

Cross-check if the order id is correct (I think it changes between re-connects), otherwise I will try to repo as soon as possible.
"How to" run:
node ./node_modules/@stoqey/ib/dist/tools/open-order.js
(use -port argument is needed)
It is the a tool print a open orders to console (https://github.com/stoqey/ib/blob/master/src/tools/open-orders.ts), so you can check if order 42 is actually there

**Comment by IldarDavletyarov** [comment]
error: `OrderId 42 that needs to be cancelled is not found`
getAllOpenOrders returns two orders with orderId=42 and orderState.status: `Submitted`

🤔🤔🤔

**Comment by mfrener** [comment]
just guessing.. is it:
> * Note: API clients cannot cancel individual orders placed by other clients.
>   * Use [[cancelAllOrders]] instead.
(https://stoqey.github.io/ib-doc/classes/ibapinext.html#cancelorder)
?
Client ID is specified on the ib.connect(id) call. https://stoqey.github.io/ib-doc/classes/ibapinext.html#connect
If you don't specify it be a static one (like b.connect(0)) it will change on each re-connect, so maybe you try to cancel an order placed by another client id? 
Although getAllOpenOrders giving two orders with same id is really strange... thought this is some kind of "unique identifier" hmm..

**Comment by IldarDavletyarov** [comment]
`ibApiNext.connect(CONST_ID)` fixed it.

Thank you ❤️
