### ISSUE TITLE
Trailing Stop Limit order?

### ISSUE THREAD

**Issue by amcintyre99** [stoqey/ib#149]
Does your lib support IBs Trailing Stop Limit order?
https://interactivebrokers.github.io/tws-api/basic_orders.html#trailingstoplimit

I looked at your doc and I see TrailingStopOrder but unsure how to use that for Trailing Stop Limit.
https://stoqey.github.io/ib-doc/classes/trailingstoporder.html

thanks,
Andrew

**Comment by amcintyre99** [comment]
Never mind. I think I see it.

It's a TRAIL LMT with TrailStopPrice, LmtPriceOffset and AuxPrice.

Please correct me if I'm wrong but I will close this.

thanks,
Andrew

**Comment by mfrener** [comment]
There is no TrailingStopLimitOder class, but the order type is supported, so you should be able to transform the IB code like:
Order order = new Order();
order.Action = action;
order.OrderType = "TRAIL LIMIT";
order.TotalQuantity = quantity;
order.TrailStopPrice = trailStopPrice;
order.LmtPriceOffset = lmtPriceOffset;
order.AuxPrice = trailingAmount;

=> 

const order: Order = {
    action,
    orderType: OrderType.TRAIL_LIMIT,
    totalQuantity: quantity,
    trailStopPrice = trailStopPrice,
    lmtPriceOffset = lmtPriceOffset,
    auxPrice = trailingAmount;
 };

**Comment by amcintyre99** [comment]
Thanks!!!
