### ISSUE TITLE
IBApiNext: example on placing order and listen to order execution

### ISSUE THREAD

**Issue by kayazinc** [stoqey/ib#153]
Is there any example on how to listen to order execution with IBApiNext?

From the document (https://stoqey.github.io/ib-doc/classes/ibapinext.html#placeneworder), to place an new order, use `placeNewOrder` which will return the order id.  

How do i listen for the order execution?  Should i use IBApi for the execution event instead?

Thanks!

**Comment by rylorin** [comment]
Hello,

you can use `getOpenOrders` which will update the order including order status each time there's any change to the order.
