### ISSUE TITLE
Can't send order to TWS

### ISSUE THREAD

**Issue by vitsy** [stoqey/ib#16]
Can't send any order to TWS with the  last version API(1.02, but can send  in more early  0.1.

Error in the encoder.ts
  if (this.serverVersion >= MIN_SERVER_VER.SOFT_DOLLAR_TIER) {
      tokens.push(order.softDollarTier.name);  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<  Can't read property name
      tokens.push(order.softDollarTier.value);
   }

Error object really without softDollarTier , but looks like it needs to set some value, or  what is the way to solve the problem with softDollarTier. Variants like softDollarTier = {} , or softDollarTier ={name:'', value:''} are not help. 

Thanks,
Victor

**Comment by ceddybi** [comment]
@vitsy thank you so much for reporting this Victor, I'll cc @mfrener our lead on the newer version to check it out, in the meantime feel free to use the earlier version, please don't hesitate to share a fix in case you run into it.

**Comment by mfrener** [comment]
There was no strict="true" on the tsconfig, but was kind of relaying that is there w/o actually checking.. 
Result is a about of un-checked optional chains. Have added strict="true" to and fixed all the new compile errors, including the 
tokens.push(order.softDollarTier.name)
--> should be:
tokens.push(order.softDollarTier?.name ? order.softDollarTier.name: ""), so undefined softDollarTier will translate to empty token.

There is a PR open https://github.com/stoqey/ib/pull/18, however I will not be able to actually test it before ~Wednesday.

@vitsy if you want test fix already so we can merged it, you can do so:
Checkout https://github.com/stoqey/ib/tree/bugfix/issue-16 branch, do "npm run build" and update your  node_modules/@stoqey/ib folder with /dist folder as generted by the npm build  (see https://github.com/stoqey/ib/wiki/Developer-Guide how to build).

**Comment by vitsy** [comment]
Great! 
Your pull request is solve this problem,
But i got error in the decoder .
  at Decoder.decodeMsg_TICK_PRICE (/media/victor/DOG/Charting/Optimizer/server/node_modules/@stoqey/ib/src/io/decoder.ts:347:24)
I will check more later.
Thanks! 
Victor

**Comment by mfrener** [comment]
Hmm that is strange, I'm using reqMktData / EventName.tickePrice on my own already and did had a problem so far. Let me know if you have any more info. To cross-check: the official reference code from IB we use right now https://github.com/stoqey/ib/blob/master/ref/client/EDecoder.java - our decodeMsg_TICK_PRICE must do same as their private void processTickPriceMsg(), bon in TS rather than Java.

**Comment by vitsy** [comment]
Hello !
 
Perhaps fragments from TWS logs  allow to see situation which I have.
Also please check screenshot what i have.
 
Looks like reason that 1.7976931348623157e+308 present in the tickPrice  
Filled order fields looks like : 
{
  action: 'BUY',
  lmtPrice: 96.5,
  totalQuantity: 69,
  transmit: true,
  orderType: 'LMT',
  orderRef: '["555","Procter & Gamble Company","USA","kkb4u0qo"]',
  outsideRth: true
}
 
 
Thanks,
Victor
  
>Суббота, 23 января 2021, 20:06 +03:00 от Matthias Frener <notifications@github.com>:
> 
> 
>Hmm that is strange, I'm using reqMktData / EventName.tickePrice on my own already and did had a problem so far. Let me know if you have any more info. To cross-check: the official reference code from IB we use right now  https://github.com/stoqey/ib/blob/master/ref/client/EDecoder.java - our decodeMsg_TICK_PRICE must do same as their private void processTickPriceMsg(), bon in TS rather than Java.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
 
 
--
Виктор Цыба

**Comment by mfrener** [comment]
Hey Victor.

In general, a value of 1.7976931348623157e+308 (= Number.MAX_VALUE) on tick values means that this values is not available right now. Can have multiple reasons, i.e. you are outside trading-hours and have request real-time, but not the frozen data (see https://stoqey.github.io/ib-doc/classes/ibapi.html#reqmarketdatatype), or you don't have market data for it all, or... many reason.

So if you get Number.MAX_VALUE value on any of the events (such as tickPrice, tickSize, tickOptionComputation, pnl, ...) is means this value is not available from IB right now.
If you can see that value on TWS but on via API, cross check https://stoqey.github.io/ib-doc/classes/ibapi.html#reqmarketdatatype

**Comment by vitsy** [comment]
Ok  you right, but suppose that better when this situation can be proccesed inside your API  ( as far decoder.ts  is inner part of API) I mean that decoder must continue work.
But in any case thanks!
Suppose that my issue can be closed
 
Thanks,
Victor

  
>Воскресенье, 24 января 2021, 16:11 +03:00 от Matthias Frener <notifications@github.com>:
> 
> 
>Hey Victor.
>In general, a value of 1.7976931348623157e+308 (= Number.MAX_VALUE) on tick values means that this values is not available right now. Can have multiple reasons, i.e. you are outside trading-hours and have request real-time, but not the frozen data (see  https://stoqey.github.io/ib-doc/classes/ibapi.html#reqmarketdatatype ), or you don't have market data for it all, or... many reason.
>So if you get Number.MAX_VALUE value on any of the events (such as tickPrice, tickSize, tickOptionComputation, pnl, ...) is means this value is not available from IB right now.
>If you can see that value on TWS but on via API, cross check  https://stoqey.github.io/ib-doc/classes/ibapi.html#reqmarketdatatype
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Виктор Цыба

**Comment by mfrener** [comment]
> Ok  you right, but suppose that better when this situation can be proccesed inside your API  ( as far decoder.ts  is inner part of API) I mean that decoder must continue work. But in any case thanks! Suppose that my issue can be closed   Thanks, Victor  
> Воскресенье, 24 января 2021, 16:11 +03:00 от Matthias Frener ***@***.***>:     Hey Victor. In general, a value of 1.7976931348623157e+308 (= Number.MAX_VALUE) on tick values means that this values is not available right now. Can have multiple reasons, i.e. you are outside trading-hours and have request real-time, but not the frozen data (see https://stoqey.github.io/ib-doc/classes/ibapi.html#reqmarketdatatype ), or you don't have market data for it all, or... many reason. So if you get Number.MAX_VALUE value on any of the events (such as tickPrice, tickSize, tickOptionComputation, pnl, ...) is means this value is not available from IB right now. If you can see that value on TWS but on via API, cross check https://stoqey.github.io/ib-doc/classes/ibapi.html#reqmarketdatatype — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub , or unsubscribe .
>     -- Виктор Цыба

I was also thinking about doing some special handling inside the decoder for that, i.e. use number|undefined types on return undefined instead of Number.MAX_VALUE... but this would diverge from official IB API. In their Java API use Double.MAX_VALUE, we use Number.MAX_VALUE in our TypeScript clone. So if Java an TS is in sync, also if there would be better solutions for that in TS.

Thanks for feedback & testing - waiting for PR review than it will be merged to master.

**Comment by mfrener** [comment]
PR is merged to master, npm update will follow soon.
Thanks for reporting!

**Comment by vitsy** [comment]
Thanks!
