### ISSUE TITLE
connect issue

### ISSUE THREAD

**Issue by mafianekcek** [stoqey/ib#162]
Hi, I am facing a problem which I have tested even with this simple script:
```
const IBAPI = require("@stoqey/ib");
const ib = new IBAPI.IBApi({
	clientId: 1,
	host: '127.0.0.1',
	port: 7496
});
ib.on(IBAPI.EventName.all, (event, args) => {
	console.log(event, JSON.stringify(args))
})
ib.on(IBAPI.EventName.error, (err, code, reqId) => {
	console.error(err, code, reqId);
})

ib.connect()
```

The problem is that sometimes after run script it connects me to the API but immediately disconnects as you can see in console output:
```
[17:29:31.561] [LOG]   sent [["API\u0000",0,0,0,9,"v100..151"],"v100..151"]
[17:29:31.564] [LOG]   received [["151","20221216 17:29:41 CET"],"151\u000020221216 17:29:41 CET\u0000"]
[17:29:31.565] [LOG]   sent [[71,2,1,""],"71\u00002\u00001\u0000"]
[17:29:31.566] [LOG]   sent [[17,1],"17\u00001"]
[17:29:31.566] [LOG]   connected []
[17:29:31.566] [LOG]   server [151,"20221216 17:29:41 CET"]
[17:29:31.570] [LOG]   disconnected []
```

Do you have any ideas please? Thank you

**Comment by Tsopic** [comment]
Check out tools folder, also I'd recommend to use APINext asi in tools ;)

**Comment by mafianekcek** [comment]
Thank you for quick answer, however I am not sure what to do now with the tools, does it mean that I need to rewrite everything into APINext and normal API is just broken?

**Comment by Tsopic** [comment]
APINext relies on the original API, there must be something wrong with the
implementation.


Kontakt mafianekcek ***@***.***>) kirjutas kuupäeval R, 16.
detsember 2022 kell 18:56:

**Comment by kadyrleev** [comment]
It does sometimes fail in the way @mafianekcek described. With API you'd see that log from above and with APINext it actually throws ECONNRESET node error.

**Comment by Tsopic** [comment]
Are you sure that the API container you are using is 100% okay?

This used to be the main issue for me, before i added some reset mechanisms to ensure i'm able to connect

**Comment by kadyrleev** [comment]
@Tsopic  First of all, kudos to the greta work you've done guys! 

To be honest I'm not sure I had it done all right. Currently using Python in my projects so that was a quick test run after a conversation on one group where I suggest your package over another one.

For APINext I just have built it to production and run `node account-summary.js` script from `dist/tools` with paper IB Gateway running on localhost. Every now and then it fails to connect.

OS: MacOS 12.6.2
Node: v18.11.0
NPM: 8.19.3
IB Gateway: 10.19

**Comment by Tsopic** [comment]
You can always check the logs of the API if there are any errors there regarding connection, I'm running this for local testing and "prod" use:

https://github.com/waytrade/ib-gateway-docker

It somewhat sucks...
Must restart every night + have a health check service to see if it's actually accepting connections and 100% okay

**Comment by kadyrleev** [comment]
@Tsopic Hey, thanks for your reply. 
What I can confirm is that the connection is closed and you actually see it in that log posted at the top of this thread and no client log is then available. And APINext throws `ECONNRESET` which comes from node `net` module I assume.  I'll check the main API log when have time to run it again.

I know `waytrade/ib-gateway-docker` - good effort too!

**Comment by rylorin** [comment]
I also have the same problem when connecting to my local TWS running en MacOS 13. After a few attempts it generally connect successfully.
I don't have this problem when connecting to a remote IBGW running on Linux.
This problem may be not related to our API.

**Comment by Tsopic** [comment]
I think `socat` smoothens the connection for IBGW. The point of failure is usually the IB Gateway indeed.

**Comment by rylorin** [comment]
Can you give a try to `connect-issue` branch and report if you see (or not) any improvement?

**Comment by ThierrySans** [comment]
I had the same problem until I checked the follow setting on my TW:

API > Settings > Reject messages above maximum allowed message rate
