### ISSUE TITLE
Searching securities

### ISSUE THREAD

**Issue by Earu** [stoqey/ib#170]
As requested, I'm moving this issue on this repo (https://github.com/stoqey/ibkr/issues/91).

--
Hi there, first off I'd like to say amazing work on that wrapper so far. Being new to IBKR and their API I was wondering if there was any way to search securities via their API, and if there is does that wrapper implement it ?

**Comment by Tsopic** [comment]
Bruh, use chatGPT

**Comment by Earu** [comment]
As much as I would like to rely on ChatGPT for questions like these it's unfortunately a text model before all, not an information model. I'm asking here as you guy seem like qualified people to answer this question, if that isn't the case feel free to close this issue then 🙂

**Comment by Earu** [comment]
Got around to dig more into this today, you can do this with the `reqMatchingSymbols` function and await for `symbolSamples` (https://interactivebrokers.github.io/tws-api/matching_symbols.html). Thanks for nothing Mr.GPT absolutely invalid code as expected but I did try your wonderful recommendation 😂

![image](https://github.com/stoqey/ib/assets/20880060/b09d8470-6953-4bdc-b010-93338920a8b8)
