### ISSUE TITLE
EventName.info missing id

### ISSUE THREAD

**Issue by mafianekcek** [stoqey/ib#172]
Hello, could you please add the reqId and errorCode to the ib.on(EventName.info ?
The reqId (-1) and ErrorCore (2158) is being received so it should be easy for you to add it
```
received [
  [
    '4',
    '2',
    '-1',
    '2158',
    'Sec-def data farm connection is OK:secdefil',
    ''
  ],
  '4\x002\x00-1\x002158\x00Sec-def data farm connection is OK:secdefil\x00\x00'
]
```
You may ask why? Its simple, I am building a bot for people and I need to know about every info, and there are many languages in the TWS and also on its white label, so message only is not practical because it would be different in each language, however code is always the same.
Right now there is only message listener but the error code is very important for me and I would be glad if you could add it there.
Thank you

**Comment by Tsopic** [comment]
You are welcome to push PR

**Comment by Tsopic** [comment]
Seems ok, the compiler eats it xD

**Comment by mafianekcek** [comment]
Perfect, thank you for fast merge. We can close this issue :)
