### ISSUE TITLE
How to get User Account Summary with specific IB Account Number ?

### ISSUE THREAD

**Issue by shaheem-khanzada** [stoqey/ib#175]
Hi, i am using stripe webhooks and in that i need to get user Ib Account Summary by account id so i can check his balance and all and do the logic, any help will be appreciated.

**Comment by rylorin** [comment]
How can we help?
I'm not sure this project is the solution to your use case.
How do you want to "get user Ib Account Summary by account id ... balance"? this is private information

**Comment by rylorin** [comment]
Closed, not an Api Next issue.
