### ISSUE TITLE
Error requesting market data for options contract - When the local symbol field is empty, please fill the following fields (right, strike, expiry)

### ISSUE THREAD

**Issue by rlmomin** [stoqey/ib#179]
I have a market data subscription for equities and options.  If I submit a reqMktData for an options contract, I keep getting an error message 
`"Error validating request.-'b1' : cause - When the local symbol field is empty, please fill the following fields (right, strike, expiry) - code: 321 - reqId: 1".`

Sending a market data request for stocks works fine but its only with options where I get an error:  Below is my request:

`let contract = new Option('NVDA', '20230713', 440, OptionType.Call);`

Once I received the 'connected' event, I send the following:
`ib.reqMarketDataType(4); `
  `ib.reqMktData(1, contract, "", false, false, [])`

Prior to sending the mktdata request, I console logged the contract detail to confirm I have the fields filled out
`Option {`
  `symbol: 'NVDA',`
  `expiry: '20230713',`
  `strike: 440,`
  `right: 'C',`
  `exchange: 'SMART',`
  `currency: 'USD',`
 `secType: 'OPT',`
 `multiplier: 100`
}`

Any help or guidance would be appreciated.

**Comment by rylorin** [comment]
Hello,
You should try to call `reqContractDetails` first, then call `reqMktData` with the resulting contract.
Let us know if it works
