### ISSUE TITLE
TypeError: path.resolve is not a function

### ISSUE THREAD

**Issue by calelloa** [stoqey/ib#184]
I am trying to use the api in a nextjs project and this error appears.

I am not sure if I can use this api to obtain information of IB using IB gateway.

Thanks.

**Comment by cmmartin** [comment]
This is a node.js library. It's meant to be run on a server not a browser. You can use it in nextjs but only in server side code (api routes or `getServerSideProps`, etc)

**Comment by rylorin** [comment]
Closed, not an Api Next issue.
