### ISSUE TITLE
Update the documentation

### ISSUE THREAD

**Issue by sami286** [stoqey/ib#199]
The documentation is updated in code but hasn't been deployed to GH pages for almost 2 years.
I've cloned the repo and run `npm run doc` to verify that the generated documentation includes the latest changes.

### EXAMPLE
The current documentation for [IBApiNext](https://stoqey.github.io/ib-doc/classes/ibapinext.html) does not include references to the `getMatchingSymbols(...)` method (you can try to Ctrl+F for it) but it is included in the actual typedoc code comments.

When regenerating the project docs, this missing method appeared:
![image](https://github.com/stoqey/ib/assets/11246472/4ac6aae2-8e69-4225-9b22-3eb46c1e7fc9)

### ACTIONS
The code itself its ok, the only thing we need to do is to deploy an updated version to GH pages at github.com/stoqey/stoqey.github.io/

**Comment by Tsopic** [comment]
Can you suggest a working code to deploy it with GH Action automatically on merge to main?

**Comment by Tsopic** [comment]
Thanks for the contribution, I've added you as a collaborator. Feel free to add the gen + CI

**Comment by sami286** [comment]
Closing this for now as docs have been updated to reflect latest code comments.
The mentioned `getMatchingSymbols(...)` used as an example now exists:
![image](https://github.com/stoqey/ib/assets/11246472/2d25338d-f943-4fc3-9635-22d24c07d304)

Will open a new issue/PR for the CI integration whenever I can :)
