### ISSUE TITLE
Decoding error on COMPLETED_ORDER

### ISSUE THREAD

**Issue by kchamp** [stoqey/ib#201]
Decoding error on COMPLETED_ORDER: unprocessed data left on queue (["","100","0.02","","",null]). Please report to https://github.com/stoqey/ib - code: 505 - reqId: -1

**Comment by rylorin** [comment]
Hello kchamp,

thanks for reporting.
I prepared a fix that I'd like to test, therefore could you provide us a test case so I can reproduce the problem and test the fix.

Thanks
