### ISSUE TITLE
Add support rxjs

### ISSUE THREAD

**Issue by mfrener** [stoqey/ib#22]
Backlog item:
The original IB API has a request + a callback (we have EventEmitter not callback) design, which is very old-school and a f*cking pain in the ass to use..
We can still keep that API in order to be compatible with IB API but in addition we should offer rxjs.

Goals is to allow both models, example:
1) Traditional via EventEmitter:
// register event receiver to receive events and log if it is PnL request 43
ib.on(EventName.pnl, (reqId: number, pnl: number) => {
   if (reqId==43) {
     console.log(pnl);
   }
});
// start PnL request 43
ib.reqPnL(43, account);

2) To be added, via rxjs:
// call request function and get an rxjs Observable 
ib.reqPnL(account).subscribe((pnl) => console.log(pnl));

**Comment by Tsopic** [comment]
rxjs seems like a lot cleaner option for sure. Love it.

**Comment by mfrener** [comment]
I have actually already started with this, but on the IBPlugin on my app. Have an IBApiNext class there (derives from IBApi) that implements re-connect handling (if connection drops, it will re-connect after [n] seconds) and it adds rxjs wrappers that stay functional also during reconnect (it will re-request open subscription on gateway after a reconnect). 
Thinking about doing PR for this after finished. So we would basically have two classes: IBApi is the API as defined by IB. The old-school way. IBApiNext (or IBApiRxjs?) does use IBApi and provide rxjs wrappers + auto re-connect handling (kind of a toolbox class in parallel to the actually API).

**Comment by Tsopic** [comment]
Holy moly. That seems like replacing wooden wheels with new-age wheels on a bike. Very much looking forward to it.

**Comment by mfrener** [comment]
This will be handled on "IBApiNext" ticket https://github.com/stoqey/ib/issues/38
