### ISSUE TITLE
reqMarketRule in ibnext

### ISSUE THREAD

**Issue by tomw1808** [stoqey/ib#230]
Hi first of all, great work on the API wrapper. I am using it on and off to trade an ASX smaller stocks privately.

I have mostly done everything using IBApiNext and try to stay away from the normal API right now. 

On a lot of contracts that I trade there are varying minimum price increments and the contract details "minTick" doesn't work for that. Apparently I need to query the reqMarketRule and extract the minTick from there somehow. However, that doesn't seem to be implemented in IBApiNext (or maybe I missed it?). I was wondering if there are any plans to add reqMarketRule in the IBApiNext project, or if its better to use the normal API for now and somehow wrap that in a request with a promise that resolves when the value is returned as event.

Thanks!
Thomas

**Comment by rylorin** [comment]
Hello Thomas,

Thank you for bringing this to our attention.

After reviewing the situation, it appears that this call has not been implemented yet. I’ve started looking into it, and while the implementation itself seems straightforward, it has uncovered some additional issues that I’m currently addressing.

I appreciate your patience, and I’ll aim to publish the implementation by late next week.

Best regards,
Ronan
