### ISSUE TITLE
support for account with contracts in multiple currencies

### ISSUE THREAD

**Issue by bayareacoder** [stoqey/ib#53]
I've been looking at the api-next branch, which is very well programmed and very clean code.

One issue is that an AccountSummary could have multiple currencies and the current data structure does not support that. IBKR could do margin calculations per currency and report tag/values by currency.

In `api-next.ts`, method: `getAccountSummary` the callback will overwrite the tag for whichever is the last reported currency:
```
const onAccountSummary = (reqId: number, account: string, tag: string, value: string, currency: string): void => {
      // get the subscription
      const subscription = this._subscriptions.get(reqId) as IBApiNextSubscription<AccountSummariesUpdate>;
      if (!subscription) {
        return;
      }

      // update cache
      const cached = subscription.value ?? new AccountSummariesUpdate();
      cached.all.getOrAdd(account).values.set(tag, { value, currency });
```

You may need an `AccountSummaryValues` map by currency.Something similar what I did here (but your code with observables is way nicer!): https://github.com/stoqey/ibkr/issues/68#issuecomment-781715475

**Comment by mfrener** [comment]
Thanks for the feedback :)
I  will change that.
I was acutally already thinking about if also need the currency on the key as well, but coudn't imagine where this makes sense (so you can get something like [Tag:"NetLiquidation"[value:1000, current:"EUR"]] and  [Tag:"NetLiquidation"[value:900 current:"USR"]] on the same account? just trying to understand the use-case on this)

**Comment by bayareacoder** [comment]
I think basically that IBKR reports everything by currency. Otherwise they would need to take into account exchange rates which is not in the API. If you trade on multiple markets you could have contracts from different currencies in your account and in that case I assume they would report multiple cash values for a single account.

Also for margin they likely have different min margin requirements by currency, or at least their API supports that, so therefore `updateAccountValue` has a similar signature so it would apply to that as well I think.

**Comment by mfrener** [comment]
I see... ;) ok, so we got one more Map https://github.com/stoqey/ib/commit/9a985571e7e5f2d73b76d642d5ffcb27c91e5a97
