### ISSUE TITLE
handling multiple simultaneous subscriptions

### ISSUE THREAD

**Issue by bayareacoder** [stoqey/ib#54]
I think below does not guarantee that an event handler (which is correctly added only once on first of multiple simultaneous subscriptions) updates all subscriptions, since basically this starts from a new empty `reqIds` Set each time you call `getPositions` so the event handler will only see 1 subscription (the first one). You'd need a `static` variable inside the method but that doesn't exist in JS...

A solution can be to have an ivar `reqIdsByEventName` in the class, and then add/remove to/from`reqIdsByEventName[EventName.position]` in your request & cancel functions as in below, as you start/stop subscriptions that would generate that event. Then in your event handler loop over all those reqIds.

This one is tricky since you don't get a `reqId` in the callback...

```
getPositions(): Observable<PositionsUpdate> {
    const requestIds = new Set<number>();

    // position event handler
    const onPosition = (account: string, contract: IContract, pos: number, avgCost: number): void => {
      const updatedPosition: Position = { account, contract, pos, avgCost };
          requestIds.forEach((id) => {
          // get subscription
          const subscription = this._subscriptions.get(id) as IBApiNextSubscription<PositionsUpdate>;
          if (!subscription) {
            return;
          }
// ...
    }

// ...
    // register event handlers
    this.registerEventHandler(EventName.position, onPosition);
// ...

    // create the subscription
    return new IBApiNextSubscription<PositionsUpdate>(
      this,
      this._subscriptions,
      (reqId) => {
        requestIds.add(reqId);
        this._api.reqPositions();
      },
      (reqId) => {
        this._api.cancelPositions();
        requestIds.delete(reqId);
      },
    ).createObservable();
```

**Comment by mfrener** [comment]
> A solution can be to have an ivar reqIdsByEventName in the class, and then add/remove
That actually a good idea. Will convert the 
``` 
/** List of all active subscriptions, with request id as key. */
  private readonly subscriptions = new Map<
    number,
    IBApiNextSubscription<unknown>
  >();
```
into a 
/** List of all active subscriptions, with request id as key. */
  private readonly subscriptions = new Map<
    EventName,
    Map<
        number,
        IBApiNextSubscription<unknown>
    >
  >();
```
It is only good to solve the issue from above, but it will also speed up event dispatching. We do not need to lookup our id in a map of all id's, but 2-level tree that groups by EventName first.

**Comment by mfrener** [comment]
btw you wanna join us slack? easier / faster to drop me a message there :D

**Comment by bayareacoder** [comment]
Having a (reqId, subscription) map by eventName seems a good idea. Then can also easily identify the cases that you have simultaneous subscriptions and return the cached data or stop the earlier subscription: in some cases the IBKR API does not allow simultaneous request calls, eg cannot simultaneously get the portfolios of different account IDs. If you're comfortable to share your email here (didn't see it on your profile, neither is it on mine) I could communicate that way.

PS
Sorry not a slack user, we use a self-hosted chat.

**Comment by mfrener** [comment]
matthias[dot]frener[at]gmail[dot]com

(i usually avoid email on public pofiles... just makes too easy for those damn spambot crawlers)

**Comment by mfrener** [comment]
Has been solved with "subscriptoin registry" features. 
Registry now maintains subscriptoins by event name and it does so always - so that special code such as on getPositions is gone. onPositions handler will get full list of open subscriptions (will always be 1 on onPositions because getPositions uses ame instanceId always, which will result in an additional Observer but no additional subscription).
