### ISSUE TITLE
Decoder missing handlers for some message ids

### ISSUE THREAD

**Issue by dalesmckay** [stoqey/ib#55]
**Issue**
The decoder is missing handlers for some message ids.
Once encountered, this causes the queue to fall out of sync for a few cycles until the application crashes.

**Source File**
https://github.com/stoqey/ib/blob/master/src/io/decoder.ts

**Code Fix**

Add the following values to `enum IN_MSG_ID`:
```javascript
REROUTE_MKT_DATA = 91,
REROUTE_MKT_DEPTH = 92,
MARKET_RULE = 93,
```

Add the following handler functions:
```javascript
    /**
     * Decode a REROUTE_MKT_DATA message from data queue and emit a rerouteMktDataReq event.
     */
    private decodeMsg_REROUTE_MKT_DATA(): void {
        const reqId    = this.readInt();
        const conId    = this.readInt();
        const exchange = this.readStr();
        this.emit(EventName.rerouteMktDataReq, reqId, conId, exchange);
    }

    /**
     * Decode a REROUTE_MKT_DEPTH message from data queue and emit a rerouteMktDepthReq event.
     */
    private decodeMsg_REROUTE_MKT_DEPTH(): void {
        const reqId    = this.readInt();
        const conId    = this.readInt();
        const exchange = this.readStr();
        this.emit(EventName.rerouteMktDepthReq, reqId, conId, exchange);
    }

    /**
     * Decode a MARKET_RULE message from data queue and emit a marketRule event.
     */
    private decodeMsg_MARKET_RULE(): void {
        const marketRuleId     = this.readInt();
        const nPriceIncrements = this.readIncrements();
        const priceIncrements  = new Array(nPriceIncrements);

        for (let ii = 0; ii < nPriceIncrements; ii++) {
            priceIncrements[ii] = {
                lowEdge   : this.readDouble(),
                increment : this.readDouble()
            };
        }

        this.emit(EventName.marketRule, marketRuleId, priceIncrements);
    }
```

Sorry, my dev environment is not setup to modify the typescript files and make a pull request.
I'm currently working around this by applying my code fix locally in my own environments using patch-package directly on the `.js` files in the node_modules folder.

**Comment by mfrener** [comment]
Thank for the fix!
I have created a PR for and also fixed the queue-out-of-sync (message buffer is now always drained if anything on decoding fails, inlcuding the ID lookup).
https://github.com/stoqey/ib/pull/56

**Comment by Tsopic** [comment]
Thanks for the code, it will be released shortly. 

cc @mfrener
