### ISSUE TITLE
_TICK_OPTION_COMPUTATION might be buggy

### ISSUE THREAD

**Issue by mfrener** [stoqey/ib#7]
Hi.
I have been using pilwon/node-ib (but will switch to your one as soon as I have time ;) ) and did run into a bug where vega option greeks did not display.
Issue is a check for > 1 that sets it to MAX_VALUE. It is not good, as vega, gamma & co can be > 1.
Think you have the same issue on Incoming.prototype._TICK_OPTION_COMPUTATION.
See my PR for node-ib https://github.com/pilwon/node-ib/pull/166

**Comment by mfrener** [comment]
Created a PR https://github.com/stoqey/ib/pull/8

**Comment by ceddybi** [comment]
@mfrener thank you for pointing that out, just merged your fix
