### ISSUE TITLE
Conditional orders raise issues when used

### ISSUE THREAD

**Issue by pbourg** [stoqey/ib#78]
We already have it on https://github.com/stoqey/ib
Have a look at https://github.com/stoqey/ib/tree/master/src/api/order/condition and pick the conditions you need.
Than set it to Oder.conditions (works similar to official TWS API Order.Conditions )

_Originally posted by @mfrener in https://github.com/stoqey/ibkr/issues/38#issuecomment-779726325_

--------------------------

First of all, thanks for the work on this very useful api.

Whatever the tests I made with conditional orders, TWS raise an issue when placing the order.

Here is the printing of the condition list (one condition) :

Placing BUY order AAPL 20230616 130 with conditions :  [
  PriceCondition {
    price: 29,
    triggerMethod: 0,
    conId: 478483723,
    exchange: 'CBOE',
    isMore: true,
    conjunctionConnection: 'o',
    type: 1
  }
]

Below the error raised;

Erreur de lecture de la demande.Message id 2989.  Unable to parse data. java.lang.NumberFormatException: For input string: "o" - code: 320 - reqId: 2989
Erreur de lecture de la demande.Message id 478483723.  Unable to parse data. java.lang.NumberFormatException: For input string: "CBOE" - code: 320 - reqId: 478483723

Please find below the whole test code.

export function test() {
  let optionType: OptionType;
  let multiplier: number;
  let orderId: number;
  let symbol: string;
  let strike: number;
  let expirationDate: string;
  let quantity: number;
  let exchange: string; 
  let conditions: Array<OrderCondition>;
  let oneCondition : OrderCondition;

  symbol = 'AAPL';
  strike = 130;
  multiplier = 100;
  orderId = nextValidID; // Actually picked from event nextValidId : .on(EventName.nextValidId...)
  optionType = OptionType.Call;
  expirationDate = '20230616';
  quantity = 1;
  exchange = 'CBOE';

  conditions = new Array<OrderCondition>()

  // Condition data
  let triggerPrice : number = 29;
  let conID : number = 478483723;
  let isMore : boolean = true;

  oneCondition = new PriceCondition(triggerPrice, TriggerMethod.Default, conID, exchange, isMore, ConjunctionConnection.OR);
  conditions.push(oneCondition);

  // Contract definition
  let contract: Contract = {
    symbol: symbol,
    exchange: exchange,
    currency: "USD",
    secType: SecType.OPT,
    right: optionType,
    lastTradeDateOrContractMonth: expirationDate,
    strike: strike,
    multiplier: multiplier,
  };

  // Order definition
  let order: Order = {
    orderType: OrderType.MKT,
    action: OrderAction.BUY,
    orderId: orderId,
    totalQuantity: quantity,
    account: Config.ACCOUNT,
    transmit: true,
    conditions: conditions // Once this conditions line removed its works
  };

  console.log(`Placing BUY order ${symbol} ${expirationDate} ${strike} with conditions : `, conditions);
  ib.placeOrder(orderId, contract, order);
}

Is it possible to have an example of how it should be implemented ?

**Comment by mfrener** [comment]
Can you cross-check if you use current version of @stoqey/ib? There has been a fix related to conditional orders 1.1.31 (
https://github.com/stoqey/ib/issues/66), current version is 1.1.40.
do `yarn upgrade @stoqey/ib@^` to pull most recent version to you project and update the package.json
If have tested it (and added PR for the test, you have some sample code). 
See here https://github.com/stoqey/ib/pull/79/files

**Comment by pbourg** [comment]
I upgraded the version using npm and it seems to work now.

Thank you again for your work and for this help
